### ISSUE TITLE
Difficulty serving Swagger API documentation

### ISSUE THREAD

**Issue by greglever** [rdidyk/falcon-swagger-ui#10]
Hi,

Using the example in the repo I have:
```
# example.py
import falcon
from falcon_swagger_ui import StaticSinkAdapter
from falcon_swagger_ui import register_swaggerui_app

SWAGGERUI_URL = '/swagger'  
SCHEMA_URL = '/swagger.json'

app = falcon.API()
app.add_sink(
    StaticSinkAdapter('/home/greg/falcon-swagger-example/schema.json'), SCHEMA_URL
)

register_swaggerui_app(app, SWAGGERUI_URL, SCHEMA_URL, config={
    'supportedSubmitMethods': ['get'],
})
```
where my schema json files already exist. if I then run `gunicorn example:app` and go to http://127.0.0.1:8000/swagger I get the following error:
```
[2017-11-30 13:51:59 +0000] [23935] [ERROR] Error handling request /swagger.json
Traceback (most recent call last):
  File "/home/greg/falcon-swagger-example/.env/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/greg/falcon-swagger-example/.env/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/greg/falcon-swagger-example/.env/local/lib/python2.7/site-packages/falcon/api.py", line 242, in __call__
    responder(req, resp, **params)
TypeError: __call__() takes exactly 4 arguments (3 given)
```
Any ideas what I'm doing wrong ?

**Comment by rdidyk** [comment]
Hi,
please refer to example: https://github.com/rdidyk/falcon-swagger-ui/blob/master/example.py#L9-L17
`StaticSinkAdapter` is just inappropriate for such cases as it's expecting `filepath` parameter when called 
(see: https://github.com/rdidyk/falcon-swagger-ui/blob/master/falcon_swagger_ui/resources.py#L98-L101)

**Comment by greglever** [comment]
Ah thanks @rdidyk I must admit I first came across this issue in January but I can see there have been some updates since then. I'll make sure to checkout the latest version of the code and try this again.

**Comment by greglever** [comment]
All working fine now, thanks a lot @rdidyk ! :smile:
