### ISSUE TITLE
Pypi Version 1.0.0 vs 1.1.1

### ISSUE THREAD

**Issue by brianbruggeman** [rdidyk/falcon-swagger-ui#11]
It appears that the version in pypi is 1.1.1, and when I install it on my development laptop, I find and install 1.1.1 (perhaps using my cache?).  However, when I attempt to click on the download from pypi, 1.1.1 is not available (404).

Additionally, I seem to be mostly miss or sometimes hit with a docker image.

Is this in flux?

**Comment by rdidyk** [comment]
hello,
current version in pypi is: **1.1.2**
you may install **1.1.1** with: `pip install falcon-swagger-ui==1.1.1`
also you may check: https://pypi.org/project/falcon-swagger-ui/ for available versions.
