### ISSUE TITLE
Disable swagger online validation 

### ISSUE THREAD

**Issue by devender-yadav** [rdidyk/falcon-swagger-ui#12]
How can I disable swagger online validation. I am seeing Error icon in swagger UI and on clicking on that it's redirecting - https://online.swagger.io/validator?url=https://dummy-host/swagger.json

Error:
```
{"schemaValidationMessages":[{"level":"error","message":"Can't read from file https://dummy-host/swagger.json"}]}
```

**Comment by rdidyk** [comment]
Hi, you should be able to set as a configuration `validatorUrl: null` and that should disable it
