### ISSUE TITLE
How to remove explore bar

### ISSUE THREAD

**Issue by carrasquel** [rdidyk/falcon-swagger-ui#17]
Greetings I have been using the package and is pretty awesome, now I'm wondering how to disable or hide the explore bar, so it is only attached to one swagger specs file.

**Comment by rdidyk** [comment]
Hello @carrasquel 
sorry for the long delay with an answer
if I got your question correctly, you can check the [layout customization section for the swagger-ui](https://github.com/swagger-api/swagger-ui/blob/master/docs/customization/custom-layout.md)
