### ISSUE TITLE
Update for Falcon 3.0.0

### ISSUE THREAD

**Issue by alanorth** [rdidyk/falcon-swagger-ui#18]
[Falcon 3.0.0b1 was released](https://falcon.readthedocs.io/en/3.0.0b1/). There are some minor changes that will need to be made in falcon-swagger-ui to make it work without deprecation notices. For example:

    falcon.util.deprecation.DeprecatedWarning: Call to deprecated property body. Please use text instead.

In this  case `resp.body` should now be `resp.text`. See the [changelog in the release notes](https://falcon.readthedocs.io/en/3.0.0b1/changes/3.0.0.html) for more.

**Comment by alanorth** [comment]
Falcon 3.0.0 was released. I'm currently using [my own fork of your repo](https://github.com/alanorth/falcon-swagger-ui) with the minor Falcon 3.0.0 fix as well as an updated Swagger (v3.38.0).

**Comment by julienlau** [comment]
Your work was merged in master : https://github.com/rdidyk/falcon-swagger-ui/pull/20#event-5456315746
