### ISSUE TITLE
How to change api version

### ISSUE THREAD

**Issue by SandoDev** [rdidyk/falcon-swagger-ui#23]
![image](https://user-images.githubusercontent.com/46248182/153308670-81cf3420-b45d-4fa0-a049-b6fd4946977f.png)
Right where it says 1.0.6, above the documentation title!
What is the parameter or key so that I can do this?

-------------

this is what i'm trying
But it does not work :(

```py
register_swaggerui_app(
    api, SWAGGERUI_URL, SCHEMA_URL,
    page_title=page_title,
    favicon_url=favicon_url,
    version="1.0.1",
    config={'supportedSubmitMethods': ['get'], }
)

```

**Comment by rdidyk** [comment]
Hi
it's showing the version from `swagger.json` file
